version: '3.8'

services:
  redis-master:
    image: redis:6.2
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf 
    volumes:
      - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf

  redis-slave:
    image: redis:6.2
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
